//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DataTablesConcept
{
    public partial class Product
    {
        #region Primitive Properties
    
        public virtual int ProductID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string ProductNumber
        {
            get;
            set;
        }
    
        public virtual bool MakeFlag
        {
            get;
            set;
        }
    
        public virtual bool FinishedGoodsFlag
        {
            get;
            set;
        }
    
        public virtual string Color
        {
            get;
            set;
        }
    
        public virtual short SafetyStockLevel
        {
            get;
            set;
        }
    
        public virtual short ReorderPoint
        {
            get;
            set;
        }
    
        public virtual decimal StandardCost
        {
            get;
            set;
        }
    
        public virtual decimal ListPrice
        {
            get;
            set;
        }
    
        public virtual string Size
        {
            get;
            set;
        }
    
        public virtual string SizeUnitMeasureCode
        {
            get;
            set;
        }
    
        public virtual string WeightUnitMeasureCode
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Weight
        {
            get;
            set;
        }
    
        public virtual int DaysToManufacture
        {
            get;
            set;
        }
    
        public virtual string ProductLine
        {
            get;
            set;
        }
    
        public virtual string Class
        {
            get;
            set;
        }
    
        public virtual string Style
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ProductSubcategoryID
        {
            get { return _productSubcategoryID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_productSubcategoryID != value)
                    {
                        if (ProductSubcategory != null && ProductSubcategory.ProductSubcategoryID != value)
                        {
                            ProductSubcategory = null;
                        }
                        _productSubcategoryID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _productSubcategoryID;
    
        public virtual Nullable<int> ProductModelID
        {
            get;
            set;
        }
    
        public virtual System.DateTime SellStartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SellEndDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DiscontinuedDate
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual int Sort
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ProductSubcategory ProductSubcategory
        {
            get { return _productSubcategory; }
            set
            {
                if (!ReferenceEquals(_productSubcategory, value))
                {
                    var previousValue = _productSubcategory;
                    _productSubcategory = value;
                    FixupProductSubcategory(previousValue);
                }
            }
        }
        private ProductSubcategory _productSubcategory;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupProductSubcategory(ProductSubcategory previousValue)
        {
            if (previousValue != null && previousValue.Products.Contains(this))
            {
                previousValue.Products.Remove(this);
            }
    
            if (ProductSubcategory != null)
            {
                if (!ProductSubcategory.Products.Contains(this))
                {
                    ProductSubcategory.Products.Add(this);
                }
                if (ProductSubcategoryID != ProductSubcategory.ProductSubcategoryID)
                {
                    ProductSubcategoryID = ProductSubcategory.ProductSubcategoryID;
                }
            }
            else if (!_settingFK)
            {
                ProductSubcategoryID = null;
            }
        }

        #endregion
    }
}
